### PR TITLE
fix: Margin supports configuring negative numbers

### LINKED ISSUE #1164: 🐛 [Bug]: margin 不支持配置负数
### Environment

chrome

### Version

latest

### Version

latest

### Link to minimal reproduction

无

### Step to reproduce

无

### What is expected

margin 支持配置负数

### What is actually happening

margin 不支持配置负数

### What is your project name

无

### Any additional comments (optional)

_No response_

### PR DESCRIPTION
**Pull request by xuanlid**
English | [简体中文](https://github.com/opentiny/tiny-engine/blob/develop/.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.zh-CN.md)

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-engine/blob/develop/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Built its own designer, fully self-validated

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Background and solution

Fixes #1164 
margin支持输入负数，常用间距不改变
image

### What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
	- Made numeric inputs more configurable by enabling a dynamic minimum value that can be set externally.
	- Enhanced spacing settings with a new logic for minimum values based on margin or padding, allowing for more precise adjustments.

### CODE REVIEW

File: packages/settings/styles/src/components/spacing/SpacingSetting.vue [hunk 1]
```diff
@@ -5,7 +5,14 @@
...
       </span>
-      <numeric-select :name="property.name" :numericalText="numericalText" @update="inputChange" />
+      <numeric-select
+        v-if="isMargin"
+        :name="property.name"
+        :numericalText="numericalText"
+        :min="-Infinity"
+        @update="inputChange"
+      />
+      <numeric-select v-if="isPadding" :name="property.name" :numericalText="numericalText" @update="inputChange" />
```
Comment (chilingling) [inline packages/settings/styles/src/components/spacing/SpacingSetting.vue]: 这样会不会好一点？

```vue
<template>
<numeric-select :name="property.name" :numericalText="numericalText" :min="minVal" @update="inputChange" />
</template>

<script>

const minVal = computed(() => isMargin.value ? -Infinity : 0)

</script>
```

**Review by chilingling — APPROVED** [review]
