### PR TITLE
fix: The tab supports editing the title and name

### LINKED ISSUE #1106: ✨ [Feature]: Tabs选项卡组件是否可以支持绑定变量！！！
### What problem does this feature solve

Environment
chrome

Version
latest

Version
latest
Tabs选项卡组件是否可以支持动态绑定变量
tabs： [
  {
    "name": "a",
    "title": "选项一"
  },
  {
    "name": "b",
    "title": "选项2"
  },
  {
    "name": "c",
    "title": "选项3"
  },
  {
    "name": "d",
    "title": "选项4"
  }
]

现在添加的标签页 name值是一个随机数!
Image

### What does the proposed API look like

支持动态绑定变量

### What is your project name

无

### PR DESCRIPTION
**Pull request by xuanlid**
English | [简体中文](https://github.com/opentiny/tiny-engine/blob/develop/.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.zh-CN.md)

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-engine/blob/develop/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Built its own designer, fully self-validated

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Background and solution

Fixes #1106 
标签页组件可以配置tab title 和 tab name
tab title —>页签名
tab name —>页签ID
image

### What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Summary by CodeRabbit

- **New Features**
  - Added a header row with labeled columns "页签标题" and "页签值".
  - Introduced inline input fields in each list item for editing titles and values.
  - Enabled dragging list items only via a specific handle icon.

- **Style**
  - Enhanced header layout with inline-flex and vertical dividers.
  - Improved spacing, alignment, and input sizing for better usability.
  - Added new background and border color variables for container customization.

### CODE REVIEW

**Review by chilingling — DISMISSED** [review]

File: packages/configurator/src/container-configurator/ContainerConfigurator.vue [hunk 1]
```diff
@@ -1,10 +1,15 @@
...
+    <div class="tabs-header">
+      <div>页签标题</div>
+      <div class="tabs-header-id">页签值</div>
+    </div>
     <meta-list-items class="list" :optionsList="children" @dragEnd="dragEnd">
       <template #content="{ data }">
         <div class="item-text">
           <div class="tiny-input">
             <tiny-input v-model="data.props.title" @update:modelValue="onTitleUpdate(data)" />
+            <tiny-input v-model="data.props.name" @update:modelValue="onTitleUpdate(data)" />
```
Comment (hexqi) [inline packages/configurator/src/container-configurator/ContainerConfigurator.vue:12]: 无法鼠标选中输入框内容，会触发拖拽

**Review by hexqi — APPROVED** [review]
