### PR TITLE
fix: url unchanged after create block

### LINKED ISSUE #1311: 🐛 [Bug]: 停留在子路由页面时，创建区块，画布没有清除父级路由的内容
### Environment

mac 12.6.7 chrome latest

### Version

latest

### Version

latest

### Link to minimal reproduction

Image

Image

### Step to reproduce

1、开启路由视图，点击子路由页面，停留在子路由页面
2、点击区块插件，新建区块
3、确认新建区块，画布未清空父级页面，只清空了子路由页面

### What is expected

_No response_

### What is actually happening

_No response_

### What is your project name

二开

### Any additional comments (optional)

_No response_

### PR DESCRIPTION
**Pull request by gene9831**
English | [简体中文](https://github.com/opentiny/tiny-engine/blob/develop/.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.zh-CN.md)

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-engine/blob/develop/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Built its own designer, fully self-validated

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Background and solution

问题现象：在设计器区块插件中，新建区块后。url blockid参数没有更新，导致画布上下文不正确，可能渲染出错误的页面
关联Bug： #1311，另外 #1312 pr修改方案并非解决url参数的问题
原因：在设计器区块插件中，新建区块后，此时新区块数据未保存到服务器，所以拿不到新区块的id。导致url参数中的blockid无法更新
解决方案：在新建区块后，立即向服务器发起请求，使用新的区块id来更新url参数。（新建页面也是类似的逻辑，所以新建页面后url可以正常更新）

### What is the current behavior?

Issue Number: N/A

### What is the new behavior?

- 在新建区块后，立即向服务器发起请求，使用新的区块id来更新url参数
- 将新建或更新区块内容成功后的Modal弹窗，修改为通知，优化UI体验
  before：
image
  aflter：
image

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved error handling when updating block categories to prevent runtime errors if a category is missing.
  - Enhanced safety checks for tenant data to avoid issues when certain fields are undefined.

- **New Features**
  - Asynchronous handling of block creation now ensures the global block ID is updated only after successful creation.
  - Notifications for block operations are now unified and provide clearer success messages.

- **Refactor**
  - Streamlined block creation and initialization by delegating to a unified meta API, allowing better promise management and more consistent behavior.
  - Updated block creation and update functions to return promises directly, improving asynchronous handling and caller control.

### CODE REVIEW

File: packages/plugins/block/src/js/blockSetting.tsx [hunk 1]
```diff
@@ -723,7 +725,7 @@ export const saveBlock = async (block) => {
     block.content.dependencies = { scripts, styles: [...styles] }
 
     const actionPromise = block.id ? updateBlock(block) : createBlock(block)
-    await actionPromise
+    return actionPromise
```
Comment (hexqi) [inline packages/plugins/block/src/js/blockSetting.tsx:730]: updateBlock没有返回promise，修改同步修改该方法

File: packages/plugins/block/src/js/blockSetting.tsx [hunk 2]
```diff
@@ -723,7 +725,7 @@ export const saveBlock = async (block) => {
     block.content.dependencies = { scripts, styles: [...styles] }
 
     const actionPromise = block.id ? updateBlock(block) : createBlock(block)
```
Comment (hexqi) [inline packages/plugins/block/src/js/blockSetting.tsx:729]: 去掉了await，async也可以去掉了

**Review by rhlin — DISMISSED** [review]

File: packages/plugins/block/src/SaveNewBlock.vue [hunk 3]
```diff
@@ -88,13 +88,13 @@ export default {
...
-      } else {
-        createEmptyBlock(formData)
-      }
-      activePlugin(PLUGIN_NAME.Materials) // ?? 疑问：新建区块后，这里为啥要激活物料
-      cancel()
+      const promise = props.fromCanvas ? createBlock(formData) : createEmptyBlock(formData)
+
+      promise.then((block) => {
+        getMetaApi(META_SERVICE.GlobalService).updateBlockId(block.id)
+        activePlugin(PLUGIN_NAME.Materials) // ?? 疑问：新建区块后，这里为啥要激活物料
```
Comment (hexqi) [inline packages/plugins/block/src/SaveNewBlock.vue]: 注释中的疑问删掉吧，创建区块后的操作一半都是搭建区块，激活物料插件主要是方便下一步搭建

**Review by hexqi — DISMISSED** [review]

**Review by hexqi — APPROVED** [review]
