### PR TITLE
fix(preview): multiple nested blocks cannot preview #663

### LINKED ISSUE #663: 🐛 [Bug]: 自定义区块和组件预览时，无法完整正确渲染出内容（组件或区块缺失）
### Environment

chrome

### Version

18.17.1

### Version

latest

### Link to minimal reproduction

涉及文件
https://github.com/opentiny/tiny-engine/blob/develop/packages/design-core/src/preview/src/preview/Preview.vue

## 取消CDN引用，和以数据库的方式部署区块情况下，编辑区域存在多个自定义区块 和组件时，点击预览，只会渲染列表中的最后一条区块数据

情况一：
1：编辑时，拖入多个自定义区块  和  多个内置组件，此时能正常渲染
微信图片_20240717151536

2：预览时，则只会渲染列表中的最后一条区块数据
微信图片_20240717145650

3：以下是我定位到的认为有问题的代码位置
微信图片_20240717145810

情况二：
1：编辑时 组件能正常渲染
微信图片_20240717152035

2：预览时： 部分组件无法正常渲染
微信图片_20240717152041

### What is expected

希望能正常渲染出编辑的内容

### What is actually happening

_No response_

### What is your project name

tiny-engine

### Any additional comments (optional)

_No response_

### PR DESCRIPTION
**Pull request by chilingling**
English | [简体中文](https://github.com/opentiny/tiny-engine/blob/develop/.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.zh-CN.md)

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-engine/blob/develop/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Built its own designer, fully self-validated

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

### What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **Enhancements**
  - Improved handling of block schemas with the introduction of an extra list for asynchronously retrieved schemas.
  - Enhanced panel generation by ensuring accurate naming conventions with the inclusion of the `.vue` extension in the panel names for blocks.

### CODE REVIEW

**Review by rhlin — APPROVED** [review]

File: packages/design-core/src/preview/src/preview/Preview.vue [hunk 1]
```diff
@@ -136,11 +142,10 @@ export default {
         },
         ...(blocks || []).map((blockSchema) => {
           return {
-            panelName: blockSchema.fileName,
+            panelName: `${blockSchema.fileName}.vue`,
```
Comment (wenmine) [inline packages/design-core/src/preview/src/preview/Preview.vue:145]: 这里的文件名写死了vue，那之后支持其他技术栈的话是不是需要改？现在相当于硬编码了？

**Review by wenmine — APPROVED** [review]
