### PR TITLE
fix: prettier format script into iife caught error

### LINKED ISSUE #1171: 🐛 [Bug]: 【重要紧急】页面JS插件中函数存在注释时保存会导致内容丢失或无法保存
### Environment

chorme 133.0.3065.92 

### Version

latest

### Version

latest

### Link to minimal reproduction

官方参考都能复现

### Step to reproduce

页面JS插件中函数存在注释时，保存会给该函数加上小括号。如果再次编辑保存，如果有多个类似函数会无法保存，如果只有一个会清空内容。
复现步骤：
1. 第一步：输出带注释的函数

Image
2. 第二步：保存，会给带注释的函数加上小括号。

Image
3. 第三步：随便做点什么改动，使保存可以操作。
情况一：两个函数，无法保存。

Image

情况二：删除另一个函数，只留一个。

Image
4. 第四步：再点击保存，内容被清空

Image

### What is expected

_No response_

### What is actually happening

_No response_

### What is your project name

无

### Any additional comments (optional)

无

### PR DESCRIPTION
**Pull request by chilingling**
English | [简体中文](https://github.com/opentiny/tiny-engine/blob/develop/.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.zh-CN.md)

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-engine/blob/develop/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Built its own designer, fully self-validated

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Background and solution

【问题描述】
如  #1171  描述

【问题分析】
使用 prettier 格式化的时候，强制使用 `!${string}`，转化成了表达式。

【修复方案】
单独 ExpressionStatement 的场景，只有 ExpressionStatement 的场景，才进行特殊处理，其他场景正常处理。

### What is the current behavior?

Issue Number: #1171 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
  - Introduced enhanced editor options including tab size, formatting on paste/type, and advanced word wrap settings in the Variable Configurator and Main components.

- **Bug Fixes**
  - Improved JavaScript code formatting to ensure accuracy by refining conditional logic for single expressions.
  - Enhanced change detection logic to account for line break differences, ensuring accurate state tracking.

- **Refactor**
  - Updated the formatting logic to handle JavaScript expressions more specifically, enhancing overall robustness.
  - Modified the confirm method in the Variable Configurator to be asynchronous, improving content processing before saving.

### CODE REVIEW

File: packages/common/js/ast.js [hunk 1]
```diff
@@ -34,11 +34,22 @@ const formatScript = (string) => {
...
-    ...prettierConfig
+    ...prettierConfig,
+    filePath: 'tiny-engine.js'
   }
   try {
-    // 低码中的编辑器大多只会输入js值，并不是一个完整的javascript表达式，无法格式化，因此需要特殊处理预格式化该种情形
-    newStr = prettier.format(`!${string}`, options).substring(1).replace(/\n$/, '')
+    const ast = string2Ast(string)
+    // javascript 在 prettier 格式化的时候，会自动在前面加上逗号“；”，因此该种情形需要特殊处理格式化
+    if (ast.program.body?.[0]?.type === 'ExpressionStatement') {
```
Comment (gene9831) [inline packages/common/js/ast.js]: 代码编辑写入表达时，比如填写应用状态的值，一般代码顶层也只会有一个表达式，只需要在这种场景(判断代码顶层只有一个表达式)采用这种方法去掉格式化自动添加的分号";"。其他编写js代码场景，比如js面板，就正常使用prettier的格式化

File: packages/common/js/ast.js [hunk 2]
```diff
@@ -34,11 +34,27 @@ const formatScript = (string) => {
...
+    filePath: 'tiny-engine.js'
   }
   try {
-    // 低码中的编辑器大多只会输入js值，并不是一个完整的javascript表达式，无法格式化，因此需要特殊处理预格式化该种情形
-    newStr = prettier.format(`!${string}`, options).substring(1).replace(/\n$/, '')
+    const ast = string2Ast(string)
+    // javascript 在 prettier 格式化的时候，会自动在前面加上逗号“；”，因此该种情形需要特殊处理格式化
+    if (ast.program.body?.length === 1 && ast.program.body?.[0]?.type === 'ExpressionStatement') {
+      // 将 javascript 表达式 包裹在 "!()" 中，格式化完成之后，再从里面取出来格式化之后的值
+      newStr = prettier.format(`!(${string})`, options).replace(/\n$/, '')
```
Comment (gene9831) [inline packages/common/js/ast.js]: 这里没有处理`\r\n`的情况，正则应该为`\r?\n`

File: packages/common/js/ast.js [hunk 3]
```diff
@@ -34,11 +34,27 @@ const formatScript = (string) => {
...
+
+      // 格式化后，仍存在包裹的 "!()"
+      if (newStr.match(/^!\(.*\)$/)) {
```
Comment (gene9831) [inline packages/common/js/ast.js]: - `.`并不能匹配到换行符，可以替换成`[\s\S]`
- 如果首行是注释，比如`// test`，第二行为`[1,2,3]`类似这种的表达式，在去掉包裹的`!()`字符后，会有缩进存在，这里似乎没有处理缩进。可以查看下面的例子https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBCAFAekwAngZxgB0oBtARgBoAmSgZgF0BKESkCABxgEtp9lQAQwBOwiAHcACiIT8UggDbjBAT35sARsMFgA1nBgBlQQFs4AGW5Q4yAGaL8cNhA0ArOGBgB1bR2QgOYThHYQA3G01tPQNDDh0rAHNkGGEAVycQRxNuOwcMuAAPDjhhbjNYRQB5Yu0YCGFJCHxuHmh-BAATVhBCmrKEGEUAFRKoEW5g3IVHNmaoBIU4AEVUiHgpmZBXfALDRMWVtZske2mMgEdV+EkxDjkQQXwAWms4DrfulMFuBUSAYQgJhMgn8igU3TmCzgAEEYCluBpUtcSpZrBsMgALGAmBReDEtYJxMBwQyyFrcUItFT+MD4dQgULpACSUHesEMYFKXGhrMMMBUi3RbECTTgPkEfhQgWCJXC3SsIRgN0ECWBQoCIhC-g0gg0cHBwtKsC83A6MAxyAAHAAGNhBS7cILK1Ugk55NiDDQms0WpC0ECpRxDXVyU6bOAmPUdd4dcyCeapFVwABi9WBcMSoKREBAAF9c0A

File: packages/common/js/ast.js [hunk 4]
```diff
@@ -34,11 +34,27 @@ const formatScript = (string) => {
   const options = {
     parser: 'babel',
     plugins: [parserBabel],
-    ...prettierConfig
+    ...prettierConfig,
+    filePath: 'tiny-engine.js'
```
Comment (hexqi) [inline packages/common/js/ast.js]: 这个filePath是必要的吗，这个是用来做什么的？

File: packages/common/js/ast.js (hunk 3 above)
Comment (chilingling) [reply packages/common/js/ast.js]: 缩进可以先忽略

File: packages/common/js/ast.js (hunk 4 above)
Comment (chilingling) [reply packages/common/js/ast.js]: 已删除

File: packages/configurator/src/variable-configurator/VariableConfigurator.vue [hunk 5]
```diff
@@ -398,14 +410,16 @@
       cancel()
     }
 
-    const confirm = () => {
-      let variableContent = state.isEditorEditMode ? editor.value?.getEditor().getValue() : state.variable
+    const confirm = async () => {
+      const editorInstance = editor.value?.getEditor()
+      await editorInstance.getAction('editor.action.formatDocument').run()
+
+      let variableContent = state.isEditorEditMode ? editorInstance.getValue() : state.variable
```
[the remark this answers is not in the document]
Comment (chilingling) [reply packages/configurator/src/variable-configurator/VariableConfigurator.vue]: Done, thanks

**Review by hexqi — APPROVED** [review]
