### PR TITLE
fix(settings): fix text wrap of bind condition

### LINKED ISSUE #370: 🐛 [Bug]: 右侧绑定元素显示隐藏的变量操作按钮，当变量名字特别长，或者写了一个函数的时候，按钮就超出页面了
### Environment

dev

### Version

20

### Version

latest

### Link to minimal reproduction

右侧绑定元素显示隐藏的变量操作按钮，当变量名字特别长，或者写了一个函数的时候，按钮就超出页面了

### Step to reproduce

右侧绑定元素显示隐藏的变量操作按钮，当变量名字特别长，或者写了一个函数的时候，按钮就超出页面了

### What is expected

_No response_

### What is actually happening

_No response_

### What is your project name

最新项目

### Any additional comments (optional)

_No response_

### PR DESCRIPTION
**Pull request by xiejay97**
Fixes #370

English | [简体中文](https://github.com/opentiny/tiny-engine/blob/develop/.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.zh-CN.md)

# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our [Commit Message Guidelines](https://github.com/opentiny/tiny-engine/blob/develop/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Built its own designer, fully self-validated

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

### What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

File: packages/settings/events/src/components/AdvanceConfig.vue [hunk 1]
```diff
@@ -4,7 +4,9 @@
       <label class="text-ellipsis-multiple">是否渲染</label>
       <div class="advanced-config-form-item">
         <meta-switch v-if="!isBind" :modelValue="condition" @update:modelValue="setConfig"> </meta-switch>
-        <div v-else class="binding-state">已绑定：{{ condition.value }}</div>
+        <div v-else class="binding-state text-ellipsis-multiple" :title="condition.value">
+          绑定：{{ condition.value }}
```
Comment (chilingling) [inline packages/settings/events/src/components/AdvanceConfig.vue]: `已绑定` 术语建议不用改

Comment (xiejay97) [reply packages/settings/events/src/components/AdvanceConfig.vue]: 已重推

**Review by chilingling — APPROVED** [review]

**Review by wenmine — APPROVED** [review]
LGTM

**Comment by kagol** [comment]
@xiejay97 下次记得给commit加上GPG签名哈~
image
